### PR TITLE
fix(homepage): update content

### PR DESCRIPTION
**Pull request by puregarlic**
# Changes introduced

Updates the heading, intro content, Exploration button content, and adds
button descriptions. Makes the homepage match this mockup:

image

## Related issue(s):

- CSE-408

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [ ] Verified that there are no issues in CircleCI
- [ ] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [ ] Requested review from the SB Reviewers team

## Reviewer checklist

- [x] Assigned yourself to the PR
- [x] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [x] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Comment by puregarlic** [comment]
This PR also contains the same change as #128, so you can either merge that one and then this one, or you can merge this one and close the other.

**Comment by bmikkelsen22** [comment]
Closes #128

**Review by bmikkelsen22 — APPROVED** [review]
Looks good! 👍

**Pull request merged**
