### PR TITLE
fix/CSE-351-filter-button-font-sizes

### PR DESCRIPTION
**Pull request by Bensonre**
# Changes introduced

change font size in button to be 18 px as requested here https://sbacjira.atlassian.net/projects/CSE/issues/CSE-351?filter=allopenissues

## Related issue(s):

- CSE-_user story or bug_
- CSE-350 (similar request for app page)

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Comment by Bensonre** [comment]
https://sbacjira.atlassian.net/projects/CSE/issues/CSE-351?filter=allopenissues is the link for this one

**Review by tnoelcke — CHANGES_REQUESTED** [review]
Please update this PR to use EM for the font size in the filter.
Thanks!

**Comment by Bensonre** [comment]
Updated!

**Review by tnoelcke — APPROVED** [review]
Nice simple solution. Looks good!

**Pull request merged**
