### PR TITLE
Feat/CSE-358 fix target page mobile

### PR DESCRIPTION
**Pull request by Bensonre**
# Changes introduced

adds a a mobile version of the title bar, adds an option component to generic page layout to add claim and target desc to mobile 

## Related issue(s):

- CSE-_user story or bug_
- CSE-_task number_

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Review by tnoelcke — CHANGES_REQUESTED** [review]
When I try to use the nav bar from the target page I get an error and then a blank screen. Please address this issue then I will review again. 

Otherwise, Looks good!

**Review by tnoelcke — APPROVED** [review]

**Comment by tnoelcke** [comment]
As it turns out the issue with the nav bar is related to different problem. So you don't need to worry about that. Please fix the merge conflicts then I will merge.

Thanks!

**Comment by Bensonre** [comment]
@tnoelcke The Snap shots fail on circle but pass locally, I am not sure how to fix this. They fail for TitleBar

**Comment by Bensonre** [comment]
Just discovered that Target and title bar on dev in storybook are broken as well that may relate

**Pull request merged**
