### PR TITLE
Fix/CSE-350-app-page-font-size

### PR DESCRIPTION
**Pull request by Bensonre**
# Changes introduced
change font size to 14px in description under photos on apps page

## Related issue(s):

- CSE-_user story or bug_
- CSE-_task number_

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Review by danvanhorn — COMMENTED** [review]
Can I get  task number for this one? It's generally against convention to use `px` for font size because it doesn't scale for mobile devices and is screen dependent. I think we should use `em` and set the global font size to a `pt` representation. That way the `em` scales accordingly in both mobile and desktop environments

**Review by danvanhorn — DISMISSED** [review]
let's talk about more about this one

**Comment by Bensonre** [comment]
https://sbacjira.atlassian.net/projects/CSE/issues/CSE-350?filter=allopenissues is the link for this one requested by Carrie

**Comment by Bensonre** [comment]
she wants a minimum of 14px, very similar for my pull request on the filter button font size

**Comment by Bensonre** [comment]
I now used em for app page, and set a global font at generic page and title of 14 px; this changes all of the storyshots, because it updates everything to 14 px unless other-wised defined. I believe this is what we wanted.

**Review by tnoelcke — APPROVED** [review]
Looks good, Thanks for setting a global font size.

**Pull request merged**
