### PR TITLE
Feat/cse 319 apps page

### PR DESCRIPTION
**Pull request by iglenwoo**
# Changes introduced

- Added apps page that uses app link component.

## Related issue(s):

- CSE-_user story or bug_
- [CSE-319](https://sbacjira.atlassian.net/browse/CSE-319)

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [x] Added new stories for created/modified components (if applicable)
- [x] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [x] Assigned yourself to the PR
- [x] Read through the changes in the `Files changed` tab
- [x] Verified that tests were written/modified
- [x] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [x] Checked out the branch and tested changes locally
- [x] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Comment by iglenwoo** [comment]
It is branched from `feat/CSE-316-app-link` and uses the component in that branch.
So, it will needs to rebase dev once that branch is merged to dev.

**Comment by iglenwoo** [comment]
This PR is ready for review since `feat/CSE-316-app-link ` branch has already merged to `dev`.

**Comment by tnoelcke** [comment]
I'm going to add real links to the resources on this page.

**Comment by Bensonre** [comment]
I added images and descriptions to Apps, aligned buttons and made images link to pages.

**Review by danvanhorn — APPROVED** [review]
I added the generic layout HOC to the export statement of the `AppsPage` as per our new convention. I also made some other various refactors to make CodeClimate happy.

**Pull request merged**
