### PR TITLE
fix(bread-crumb): darken breadcrumb in search

### PR DESCRIPTION
**Pull request by tnoelcke**
# Changes introduced
Darkens breadcrumb text in search results and underlines.

## Related issue(s):
CSE-340

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [ ] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Comment by puregarlic** [comment]
Changes to the breadcrumbs look good, but I think we might want to consider giving the search results bigger margins. Each individual result is incredibly dense, now to the point of being difficult to read.

**Comment by tnoelcke** [comment]
I've updated the styles to add some more margin to make the results a bit less dense.

**Review by puregarlic — APPROVED** [review]
Awesome, that looks better.

**Pull request merged**
