### PR TITLE
Feat/cse 316 app link

### PR DESCRIPTION
**Pull request by iglenwoo**
# Changes introduced

- Added app link components for Apps page.

## Related issue(s):

- CSE-_user story or bug_
- [CSE-316](https://sbacjira.atlassian.net/browse/CSE-316)

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [x] Added new stories for created/modified components (if applicable)
- [x] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [x] Assigned yourself to the PR
- [x] Read through the changes in the `Files changed` tab
- [x] Verified that tests were written/modified
- [x] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [x] Checked out the branch and tested changes locally
- [x] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Review by danvanhorn — CHANGES_REQUESTED** [review]
Did Smarter Balanced specify what color they want the link text to change to onHover? Right now it's gray in storybook when you hover over the link, and that isn't really compatible with usability standards.

**Comment by iglenwoo** [comment]
@danvanhorn As you mentioned, I have updated the color of the link onHover. I have also fixed to position image so that now you can see a component loaded with an actual image in storybook.

**Comment by iglenwoo** [comment]
@danvanhorn I have fixed an issue on story router. Please review this PR.

**Review by tnoelcke — CHANGES_REQUESTED** [review]
I think a better way to handle this can be found at http://sampleitems.smarterbalanced.org/ notice that in this example rather than making it bigger we underline and darken the button. I'm fairly certain that this will be more accessible and I think it looks nicer. Please use this style for the on Hover.

**Comment by iglenwoo** [comment]
@tnoelcke I have fixed the button effect on hover as you mentioned. Please review this change.

**Pull request merged**
