### PR TITLE
CSE-129 implement breadcrumb component

### PR DESCRIPTION
**Pull request by iglenwoo**
# Changes introduced

I have added breadcrumb components which will be used in the title bar and a storybook.

## Related issue(s):

- CSE-217
- CSE-129

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [x] Added new stories for created/modified components (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [ ] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [x] Assigned yourself to the PR
- [x] Read through the changes in the `Files changed` tab
- [x] Verified that tests were written/modified
- [x] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [x] Checked out the branch and tested changes locally

### CODE REVIEW

**Comment by tnoelcke** [comment]
Please resolve conflicts in .gitignore and package files.

**Comment by iglenwoo** [comment]
@tnoelcke I have resolved the conflicts in .gitignore and package files and added a snapshot.
Please review this PR again.

**Comment by tnoelcke** [comment]
Also double check that there are no accessibility issues in storybook.

**Comment by iglenwoo** [comment]
@tnoelcke I have refactored the breadcrumb implementation and updated the storybook as well.

**Review by tnoelcke — APPROVED** [review]

**Pull request merged**
