### PR TITLE
feat/CSE-424-search-page-accessibility

### PR DESCRIPTION
**Pull request by Bensonre**
# Changes introduced

adds aria-live polite regions to filter and results, now screen readers readout out the dynamic changes that occur for these areas
adds button role to reset button, now when clicked a screen reader says "reset button" 

## Related issue(s):

- CSE-424
- CSE-_task number_

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Review by danvanhorn — DISMISSED** [review]
You'll need to run the snapshot tests and review the changes made to the markup. If the changes are expected then you can update the snapshots and commit them. That's the reason why the tests are failing.

**Review by danvanhorn — DISMISSED** [review]
- The contrast for the 'Show Performance Tasks' toggle button is still not compliant.
- The text size of the 'Show Performance Tasks' toggle is set to 1em instead of the required 14pt
- When you press a filter button, the screen reader says that it is "not pressed"

**Review by tnoelcke — APPROVED** [review]
Looks good to me.

**Pull request merged**
