### PR TITLE
Feat/cse 329 generic layout target

### PR DESCRIPTION
**Pull request by tnoelcke**
# Changes introduced
This PR introduces a generic layout to all of the pages. This pr also fixes many different style issues.

## Related issue(s):
No Jira task Sorry!

## Contributor checklist

- [ ] Wrote/updated tests for introduced changes
- [ ] Added new stories for created/modified components (if applicable)
- [ ] Checked Storybook for Accessibility issues (if applicable)
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] Verified that stories were written/modified (if applicable)
- [ ] ~~Verified that Postman was updated (if applicable)~~
- [ ] Checked out the branch and tested changes locally
- [ ] Run storybook and checked that there are no accessibility issues

### CODE REVIEW

**Comment by bmikkelsen22** [comment]
@osu-cass/sb-reviewers should tests be written for this before we merge, or are we trying to get it in A$AP

**Comment by puregarlic** [comment]
How long do you think it would take you to write the tests?

**Comment by tnoelcke** [comment]
To answer your question @puregarlic The generic page is where the client is declared in a way where it can't be mocked. The generic page isn't really designed to be tested at the Page level. The Generic page it self is tested but the way we are using with the target page makes it not testable. What we really need to do is write better tests for all the components. This will take some time and will have to be an item we address after we are done with feature development.

**Review by danvanhorn — APPROVED** [review]
Good to go.

**Pull request merged**
